### ISSUE TITLE
data folder ref from lib requires it to be installed in a local .env folder

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-datasprint-2021#7]
This lib requires to be installed in a local .env folder to find the data folder which is read at init time.

Assuming a specific installation mode is not safe.
I first used pyenv which installs envs in home folder.
In such a setup, the data folder path being constructed relatively to the module path to resolved to a broken path (see stacktrace).

Possible workarounds (I don't know much about packaging):
- package data: https://packaging.python.org/guides/distributing-packages-using-setuptools/#package-data or data files   https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html
- what about a path in a config file (which could be written by install.sh with the right absolute path?)
- indicate this specific installation mode requirement in the readme
- force a local .venv folder in install.sh (although a good practice feels intrusive if chosen it has to be documented)
- ask @Yomguithereal 

```bash
(portic) paul@paul:~/dev/portic-datasprint-2021$ pip install lib/
Processing ./lib
Requirement already satisfied: networkx in /home/paul/.pyenv/versions/3.8.3/envs/portic/lib/python3.8/site-packages (from poitousprint==0.0.1) (2.5)
Requirement already satisfied: requests in /home/paul/.pyenv/versions/3.8.3/envs/portic/lib/python3.8/site-packages (from poitousprint==0.0.1) (2.25.1)
Requirement already satisfied: decorator>=4.3.0 in /home/paul/.pyenv/versions/3.8.3/envs/portic/lib/python3.8/site-packages (from networkx->poitousprint==0.0.1) (4.4.2)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/paul/.pyenv/versions/3.8.3/envs/portic/lib/python3.8/site-packages (from requests->poitousprint==0.0.1) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/paul/.pyenv/versions/3.8.3/envs/portic/lib/python3.8/site-packages (from requests->poitousprint==0.0.1) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/paul/.pyenv/versions/3.8.3/envs/portic/lib/python3.8/site-packages (from requests->poitousprint==0.0.1) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in /home/paul/.pyenv/versions/3.8.3/envs/portic/lib/python3.8/site-packages (from requests->poitousprint==0.0.1) (2.10)
Using legacy 'setup.py install' for poitousprint, since package 'wheel' is not installed.
Installing collected packages: poitousprint
  Attempting uninstall: poitousprint
    Found existing installation: poitousprint 0.0.1
    Uninstalling poitousprint-0.0.1:
      Successfully uninstalled poitousprint-0.0.1
    Running setup.py install for poitousprint ... done
Successfully installed poitousprint-0.0.1
(portic) paul@paul:~/dev/portic-datasprint-2021$ python
Python 3.8.3 (default, Jul 15 2020, 10:19:26) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from poitousprint import Portic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.pyenv/versions/portic/lib/python3.8/site-packages/poitousprint/__init__.py", line 1, in <module>
    from poitousprint.toflit import Toflit
  File "/home/paul/.pyenv/versions/portic/lib/python3.8/site-packages/poitousprint/toflit.py", line 6, in <module>
    all_flows = pkgutil.get_data(__name__, "../../data/toflit18_all_flows.csv")
  File "/home/paul/.pyenv/versions/3.8.3/lib/python3.8/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/paul/.pyenv/versions/portic/lib/python3.8/site-packages/poitousprint/../../data/toflit18_all_flows.csv'
```

**Comment by paulgirard** [comment]
Ok So as @Yomguithereal told me, I can't reproduce neither... I must have set up my env wrongly at some points.
Using pyenv + install.sh works.
